name: E2E test
on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  workflow_dispatch:
env:
  URL: ${{ vars.URL }}
  STANDARD_USER: ${{ secrets.STANDARD_USER }}
  PROBLEM_USER: ${{ vars.PROBLEM_USER }}
  LOCKED_OUT_USER: ${{ vars.LOCKED_OUT_USER }}
  PERFORMANCE_GLITCH_USER: ${{ vars.PERFORMANCE_GLITCH_USER }}
  USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          npm install
          npx playwright install chromium --with-deps
      - name: Run tests
        run: npm test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: report
          path: reports/**
          retention-days: 30
      - name: Publish HTML report
        if: ${{github.ref == 'refs/heads/master' && success() || failure() }}
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_branch: report
          publish_dir: ./reports/report
