name: E2E test
on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          npm install
          npx playwright install chrome --with-deps

      - name: Run tests
        run: npm test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: report
          path: reports/**
          retention-days: 30

      - name: test
        if: always() 
        run: echo "branch=${GITHUB_HEAD_REF}"

      - name: Publish HTML report
        if: always() && 'github.branch' == 'master'
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_branch: report
